# app and org for use with dashboard.serverless.com
app: expensee
org: randal

service:
  name: expensee-serverless

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    includeModules: false

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  profile: serverless
  stage: dev
  stackName: expensee-stack-${self:provider.stage}
  apiName: expensee-api-${self:provider.stage}
  deploymentBucket:
    name: expensee-serverless-${self:provider.region}-deploys
    tags:
      project: expensee
  deploymentPrefix: expensee-serverless
  versionFunctions: false
  stackTags:
    project: expensee

package:
  individually: true
  exclude:
    - node_modules/**

# resources: # CloudFormation template syntax
#   Resources:
#     expenses:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: expensee_expenses
#         AttributeDefinitions:
#           - AttributeName: expense_id
#             AttributeType: S
#           - AttributeName: date
#             AttributeType: N
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH
#           - AttributeName: date
#             KeyType: RANGE
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1

layers:
  libNodeModule:
    path: lib
    description: "common node_module dependencies"

functions:
  addExpense:
    handler: src/functions/addExpense.handler
    layers:
      - { Ref: LibNodeModuleLambdaLayer }
    events:
      - http:
          method: post
          path: expense
