# app and org for use with dashboard.serverless.com
app: expensee
org: randal

service:
  name: expensee-serverless

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    includeModules: false

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  profile: serverless
  stage: dev
  stackName: expensee-stack-${self:provider.stage}
  apiName: expensee-api-${self:provider.stage}
  deploymentBucket:
    name: expensee-serverless-${self:provider.region}-deploys
    tags:
      project: expensee
  deploymentPrefix: expensee-serverless
  versionFunctions: false
  stackTags:
    project: expensee

package:
  individually: true
  exclude:
    - node_modules/**

resources: # CloudFormation template syntax
  Resources:
    expenses:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: expenses
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: date
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http:
          method: get
          path: hello
  goodbye:
    handler: src/functions/goodbye.handler
    events:
      - http:
          method: get
          path: goodbye
