# app and org for use with dashboard.serverless.com
app: expensee
org: randal

service:
  name: expensee-serverless

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  webpack:
    includeModules: false
  dynamodb:
    migration:
      dir: dynamoDbMigrations
    start:
      port: 8005
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: ${self:provider.environment.DYNAMODB_CATEGORIES_TABLE_NAME}
            sources: [./dynamoDb/seeds/categories.json]
    stages:
      - dev

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  profile: serverless
  stage: dev
  stackName: expensee-stack-${self:provider.stage}
  apiName: expensee-api-${self:provider.stage}
  deploymentBucket:
    name: expensee-serverless-${self:provider.region}-deploys
    tags:
      project: expensee
  deploymentPrefix: expensee-serverless
  versionFunctions: false
  stackTags:
    project: expensee
  environment:
    DYNAMODB_EXPENSES_TABLE_NAME: expensee-expenses-${opt:stage, self:provider.stage}
    DYNAMODB_CATEGORIES_TABLE_NAME: expensee-categories-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_EXPENSES_TABLE_NAME}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_CATEGORIES_TABLE_NAME}"

package:
  individually: true
  exclude:
    - node_modules/**

resources:
  Resources:
    ExpensesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: expense_id
            AttributeType: S
          - AttributeName: date
            AttributeType: N
        KeySchema:
          - AttributeName: expense_id
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_EXPENSES_TABLE_NAME}
    CategoriesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_CATEGORIES_TABLE_NAME}

layers:
  libNodeModule:
    path: lib
    description: "common node_module dependencies"

functions:
  addCategory:
    handler: src/functions/addCategory.handler
    layers:
      - { Ref: LibNodeModuleLambdaLayer }
    events:
      - http:
          method: post
          path: category
          cors: true
  addExpense:
    handler: src/functions/addExpense.handler
    layers:
      - { Ref: LibNodeModuleLambdaLayer }
    events:
      - http:
          method: post
          path: expense
          cors: true
