
# app and org for use with dashboard.serverless.com
app: expensee
org: randal

service:
  name: expensee-serverless

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  profile: serverless
  stage: dev
  stackName: expensee-stack-${self:provider.stage}
  apiName: expensee-api-${self:provider.stage}
  deploymentPrefix: expensee-serverless
  versionFunctions: false
  stackTags:
    project: expensee

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
